### ISSUE TITLE
内核错误无法使用

### ISSUE THREAD

**Issue by Xiamo-vip** [bilibili/ailab#57]
`D:\RealCUGAN_for_win10_torch1.10.0cu111_20220227>runtime\python runtime\inference234.py
tile=5  half=True       scale=2
torch version 1.10.0+cu111
torch cuda version 11.1
total GPU number 1
_CudaDeviceProperties(name='NVIDIA GeForce GTX 760', major=3, minor=0, total_memory=2048MB, multi_processor_count=6)
Traceback (most recent call last):
  File "runtime\inference234.py", line 39, in main
    result=upscaler2x(frame,tile,cache_mode=cache_mode,alpha=alpha)[:,:,::-1]
  File "D:\RealCUGAN_for_win10_torch1.10.0cu111_20220227\runtime\upcunet_v3.py", line 1234, in __call__
    tensor = self.np2tensor(frame)
  File "D:\RealCUGAN_for_win10_torch1.10.0cu111_20220227\runtime\upcunet_v3.py", line 1227, in np2tensor
    else:return torch.from_numpy(np.transpose(np_frame, (2, 0, 1))).unsqueeze(0).to(self.device).half() / 255
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
请按任意键继续. . .`

**Comment by Xiamo-vip** [comment]
D:\RealCUGAN_for_win10_torch1.10.0cu111_20220227>runtime\python runtime\inference234.py
tile=5  half=True       scale=2
torch version 1.10.0+cu111
torch cuda version 11.1
total GPU number 1
_CudaDeviceProperties(name='NVIDIA GeForce GTX 760', major=3, minor=0, total_memory=2048MB, multi_processor_count=6)
Traceback (most recent call last):
  File "runtime\inference234.py", line 39, in main
    result=upscaler2x(frame,tile,cache_mode=cache_mode,alpha=alpha)[:,:,::-1]
  File "D:\RealCUGAN_for_win10_torch1.10.0cu111_20220227\runtime\upcunet_v3.py", line 1234, in __call__
    tensor = self.np2tensor(frame)
  File "D:\RealCUGAN_for_win10_torch1.10.0cu111_20220227\runtime\upcunet_v3.py", line 1227, in np2tensor
    else:return torch.from_numpy(np.transpose(np_frame, (2, 0, 1))).unsqueeze(0).to(self.device).half() / 255
RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
请按任意键继续. . .

**Comment by splinter21** [comment]
> `D:\RealCUGAN_for_win10_torch1.10.0cu111_20220227>runtime\python runtime\inference234.py tile=5 half=True scale=2 torch version 1.10.0+cu111 torch cuda version 11.1 total GPU number 1 _CudaDeviceProperties(name='NVIDIA GeForce GTX 760', major=3, minor=0, total_memory=2048MB, multi_processor_count=6) Traceback (most recent call last): File "runtime\inference234.py", line 39, in main result=upscaler2x(frame,tile,cache_mode=cache_mode,alpha=alpha)[:,:,::-1] File "D:\RealCUGAN_for_win10_torch1.10.0cu111_20220227\runtime\upcunet_v3.py", line 1234, in __call__ tensor = self.np2tensor(frame) File "D:\RealCUGAN_for_win10_torch1.10.0cu111_20220227\runtime\upcunet_v3.py", line 1227, in np2tensor else:return torch.from_numpy(np.transpose(np_frame, (2, 0, 1))).unsqueeze(0).to(self.device).half() / 255 RuntimeError: CUDA error: no kernel image is available for execution on the device CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. 请按任意键继续. . .`

@Xiamo-vip https://github.com/bilibili/ailab/tree/main/Real-CUGAN#系统环境
这里写的小于20系的显卡建议用小包
您试试下载小包试试呢？

**Comment by lj1995-computer-vision** [comment]
> `D:\RealCUGAN_for_win10_torch1.10.0cu111_20220227>runtime\python runtime\inference234.py tile=5 half=True scale=2 torch version 1.10.0+cu111 torch cuda version 11.1 total GPU number 1 _CudaDeviceProperties(name='NVIDIA GeForce GTX 760', major=3, minor=0, total_memory=2048MB, multi_processor_count=6) Traceback (most recent call last): File "runtime\inference234.py", line 39, in main result=upscaler2x(frame,tile,cache_mode=cache_mode,alpha=alpha)[:,:,::-1] File "D:\RealCUGAN_for_win10_torch1.10.0cu111_20220227\runtime\upcunet_v3.py", line 1234, in __call__ tensor = self.np2tensor(frame) File "D:\RealCUGAN_for_win10_torch1.10.0cu111_20220227\runtime\upcunet_v3.py", line 1227, in np2tensor else:return torch.from_numpy(np.transpose(np_frame, (2, 0, 1))).unsqueeze(0).to(self.device).half() / 255 RuntimeError: CUDA error: no kernel image is available for execution on the device CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. 请按任意键继续. . .`

@Xiamo-vip 
https://github.com/bilibili/ailab/tree/main/Real-CUGAN#系统环境
这里写的小于20系的显卡建议用小包
您试试下载小包试试呢？

**Comment by Xiamo-vip** [comment]
> > `D:\RealCUGAN_for_win10_torch1.10.0cu111_20220227>runtime\python runtime\inference234.py tile=5 half=True scale=2 torch version 1.10.0+cu111 torch cuda version 11.1 total GPU number 1 _CudaDeviceProperties(name='NVIDIA GeForce GTX 760', major=3, minor=0, total_memory=2048MB, multi_processor_count=6) Traceback (most recent call last): File "runtime\inference234.py", line 39, in main result=upscaler2x(frame,tile,cache_mode=cache_mode,alpha=alpha)[:,:,::-1] File "D:\RealCUGAN_for_win10_torch1.10.0cu111_20220227\runtime\upcunet_v3.py", line 1234, in __call__ tensor = self.np2tensor(frame) File "D:\RealCUGAN_for_win10_torch1.10.0cu111_20220227\runtime\upcunet_v3.py", line 1227, in np2tensor else:return torch.from_numpy(np.transpose(np_frame, (2, 0, 1))).unsqueeze(0).to(self.device).half() / 255 RuntimeError: CUDA error: no kernel image is available for execution on the device CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. 请按任意键继续. . .`
> 
> @ Xiamo-vip.com/bilibili/ailab/tree/Real-#系统环境在这里写的 [https:](https://github.com/bilibili/ailab/tree/main/Real-CUGAN#%E7%B3%BB%E7%BB%9F%E7%8E%AF%E5%A2%83) // 20系的显卡建议用小包您下载小包用吗？

小包？是压缩包比较小的那个吗？

**Comment by Xiamo-vip** [comment]
> > > `D:\RealCUGAN_for_win10_torch1.10.0cu111_20220227>runtime\python runtime\inference234.py tile=5 half=True scale=2 torch version 1.10.0+cu111 torch cuda version 11.1 total GPU number 1 _CudaDeviceProperties(name='NVIDIA GeForce GTX 760', major=3, minor=0, total_memory=2048MB, multi_processor_count=6) Traceback (most recent call last): File "runtime\inference234.py", line 39, in main result=upscaler2x(frame,tile,cache_mode=cache_mode,alpha=alpha)[:,:,::-1] File "D:\RealCUGAN_for_win10_torch1.10.0cu111_20220227\runtime\upcunet_v3.py", line 1234, in __call__ tensor = self.np2tensor(frame) File "D:\RealCUGAN_for_win10_torch1.10.0cu111_20220227\runtime\upcunet_v3.py", line 1227, in np2tensor else:return torch.from_numpy(np.transpose(np_frame, (2, 0, 1))).unsqueeze(0).to(self.device).half() / 255 RuntimeError: CUDA error: no kernel image is available for execution on the device CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect. For debugging consider passing CUDA_LAUNCH_BLOCKING=1. 请按任意键继续. . .`
> > 
> > 
> > @Xiamo-vip.com/bilibili/ailab/tree/Real-#系统环境在这里小写的[https:](https://github.com/bilibili/ailab/tree/main/Real-CUGAN#%E7%B3%BB%E7%BB%9F%E7%8E%AF%E5%A2%83) //20系的显卡建议用包你下载小包用吗？
> 
> 小包？是压缩包比较流行的那个吗？

D:\RealCUGAN_for_win10_torch1.0.0cu100_20220227>runtime\python runtime\inference234.py
tile=5  half=True       scale=2
torch version 1.0.0
torch cuda version 10.0
total GPU number 1
_CudaDeviceProperties(name='NVIDIA GeForce GTX 760', major=3, minor=0, total_memory=2048MB, multi_processor_count=6)
Traceback (most recent call last):
  File "runtime\inference234.py", line 39, in main
    result=upscaler2x(frame,tile,cache_mode=cache_mode,alpha=alpha)[:,:,::-1]
  File "D:\RealCUGAN_for_win10_torch1.0.0cu100_20220227\runtime\upcunet_v3.py", line 1234, in __call__
    tensor = self.np2tensor(frame)
  File "D:\RealCUGAN_for_win10_torch1.0.0cu100_20220227\runtime\upcunet_v3.py", line 1227, in np2tensor
    else:return torch.from_numpy(np.transpose(np_frame, (2, 0, 1))).unsqueeze(0).to(self.device).half() / 255
RuntimeError: CUDA error: no kernel image is available for execution on the device
