### ISSUE TITLE
大佬！有时间更新下VS版本的说明，辛苦了。

### ISSUE THREAD

**Issue by feaonal** [bilibili/ailab#82]
大佬！有时间更新下VS版本的说明，辛苦了。

下载了5月35日(-_-)更新的模型和VS插件，运行报错

**使用参数**
upscaler=RealWaifuUpScaler(3,r'E:\apps\weightspro\pro-no-denoise3x-up3x.pth',True,"cuda:0",1)#scale,pth,half,device,title

**报错：**
2022-06-04 11:32:08.486
Failed to evaluate the script:
Python exception: Error(s) in loading state_dict for UpCunet3x:
Unexpected key(s) in state_dict: "pro". 

Traceback (most recent call last):
File "src\cython\vapoursynth.pyx", line 2832, in vapoursynth._vpy_evaluate
File "src\cython\vapoursynth.pyx", line 2833, in vapoursynth._vpy_evaluate
File "C:/Users/feaon/OneDrive/VS/RealCuganPro-bilibiliAIlab.vpy", line 11, in 
upscaler=RealWaifuUpScaler(3,r'E:\apps\weightspro\pro-no-denoise3x-up3x.pth',True,"cuda:0",1)#scale-weight_path-half-device-tile_mode-cache_mode-alpha
File "C:\Users\feaon\AppData\Local\Programs\Python\Python39\lib\site-packages\upcunet_v3_vs.py", line 777, in __init__
self.model.load_state_dict(weight, strict=True)
File "C:\Users\feaon\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\nn\modules\module.py", line 1482, in load_state_dict
raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for UpCunet3x:
Unexpected key(s) in state_dict: "pro".

**Comment by lj1995-computer-vision** [comment]
我还没来得及更新，今天吧。

**Comment by lj1995-computer-vision** [comment]
今天更不了了，间歇性连不上。

**Comment by feaonal** [comment]
> 今天更不了了，间歇性连不上。

谢谢！
